export const issues = [
  {
    id: crypto.randomUUID(),
    number: "issue-7",
    name: "Issue #7",
    year: 2022,
    image: "https://backstagetalks.com/img/backstagetalks_cover_issue_7.png",
    storage: true,
    link: "https://brot.sk/products/backstage-talks-issue-7",
    color: "#f6618d",
  },

  {
    id: crypto.randomUUID(),
    number: "issue-6",
    name: "Issue #6",
    year: 2021,
    image: "https://backstagetalks.com/img/backstagetalks_cover_issue_6.png",
    storage: true,
    link: "https://brot.sk/products/backstage-talks-issue-6",
    color: "#ffffff",
  },
  {
    id: crypto.randomUUID(),
    number: "issue-5",
    name: "Issue #5",
    year: 2020,
    image: "https://backstagetalks.com/img/backstagetalks_cover_issue_5.png",
    storage: true,
    link: "https://brot.sk/products/backstage-talks-5",
    color: "#00c1b5",
  },
  {
    id: crypto.randomUUID(),
    number: "issue-4",
    name: "Issue #4",
    year: 2019,
    image: "https://backstagetalks.com/img/backstagetalks_cover_issue_4.png",
    storage: false,
    link: "",
    color: "#ff651a",
  },

  {
    id: crypto.randomUUID(),
    number: "issue-3",
    name: "Issue #3",
    year: 2018,
    image: "https://backstagetalks.com/img/backstagetalks_cover_issue_3.png",
    storage: true,
    link: "https://brot.sk/products/backstage-talks-3",
    color: "#ffbe00",
  },
  {
    id: crypto.randomUUID(),
    number: "issue-2",
    name: "Issue #2",
    year: 2017,
    image: "https://backstagetalks.com/img/backstagetalks_cover2017.png",
    storage: true,
    link: "https://brot.sk/products/backstage-talks-2",
    color: "#1d3fbb",
  },
  {
    id: crypto.randomUUID(),
    number: "issue-1",
    name: "Issue #1",
    year: 2016,
    image: "https://backstagetalks.com/img/backstagetalks_cover2016_n.png",
    storage: false,
    link: "",
    color: "#e30512",
  },
];
